SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SUM(S.SALES * B.PRICE)) AS SALES FROM BOOK AS B
    JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
    JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC

