SELECT ID
FROM
    (SELECT E1.ID AS 'ID',  -- 1세대
           E1.PARENT_ID AS 'SECOND', -- 2세대 
           E2.PARENT_ID AS 'THIRD', -- 3세대
           E3.PARENT_ID AS 'FOURTH' -- 4세대
    FROM ECOLI_DATA AS E1
    LEFT JOIN ECOLI_DATA AS E2 ON E1.PARENT_ID = E2.ID -- E2의 ID는 2세대
    LEFT JOIN ECOLI_DATA AS E3 ON E2.PARENT_ID = E3.ID) AS TEMP -- E3의 ID는 3세대
WHERE (THIRD IS NOT NULL) AND (FOURTH IS NULL) -- 3세대는 null이 아니고 4세대는 null인 ID를...
ORDER BY 1 ASC