SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100, 0) AS FEE FROM CAR_RENTAL_COMPANY_CAR C

JOIN (
    SELECT CAR_ID, START_DATE, END_DATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING MAX(END_DATE) < '2022-11-01'
) H ON C.CAR_ID = H.CAR_ID
LEFT JOIN (
    select car_type, discount_rate 
    from car_rental_company_discount_plan
    where car_type in ('세단', 'SUV')
    and duration_type like '30%'
) P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV")
AND ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100, 0) >= 500000 
AND ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100, 0) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;