SELECT 
    A.ID, 
    CASE WHEN (B.RANKED / TOTAL <= 0.25) THEN "CRITICAL"
    WHEN (B.RANKED / TOTAL <= 0.5) THEN 'HIGH'
    WHEN (B.RANKED / TOTAL <= 0.75) THEN "MEDIUM"
    ELSE 'LOW' END AS COLONY_NAME
    # A.SIZE_OF_COLONY,
    # B.RANKED
FROM 
    ECOLI_DATA A
LEFT JOIN
    (SELECT
        ID, 
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKED,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTAL
    FROM ECOLI_DATA) B
ON A.ID = B.ID
ORDER BY A.ID;