SELECT 
    (CASE 
            WHEN M.MONTH <= 3 THEN '1Q'
            WHEN M.MONTH <= 6 THEN '2Q'
            WHEN M.MONTH <= 9 THEN '3Q'
            WHEN M.MONTH <= 12 THEN '4Q' END) AS QUARTER,
    COUNT(DISTINCT ID) AS ECOLI_COUNT
FROM 
    ECOLI_DATA E 
    LEFT JOIN
        (SELECT MONTH(DIFFERENTIATION_DATE) AS MONTH FROM ECOLI_DATA) M
ON MONTH(E.DIFFERENTIATION_DATE) = M.MONTH
GROUP BY QUARTER;