SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT) * P.PRICE) AS TOTAL_SALES 
FROM FOOD_PRODUCT AS P
LEFT JOIN FOOD_ORDER AS O
ON O.PRODUCT_ID = P.PRODUCT_ID 
WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;