SELECT A.FLAVOR 
FROM FIRST_HALF AS A 
    LEFT JOIN JULY AS B
    ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) DESC
LIMIT 3;
# FIRST_HALF 와 JULY 테이블을 조인 - FLAVOR에 맞춰 TOTAL_ORDER 모두 합계 계산
# RANK 통해 상위 3개만 AS FLAVOR 이름으로 리턴