WITH RECURSIVE A AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM A
    WHERE HOUR < 23 
)

SELECT 
    HOUR AS HOUR, 
    COUNT(ANIMAL_ID) AS COUNT 
FROM 
    A LEFT JOIN ANIMAL_OUTS B
ON A.HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR ASC;