SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (SELECT M.MEMBER_ID AS ID, COUNT(*) AS CNT
        FROM 
            MEMBER_PROFILE AS M
        LEFT JOIN
            REST_REVIEW AS R
            ON M.MEMBER_ID = R.MEMBER_ID
        GROUP BY M.MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1) AS A
LEFT JOIN MEMBER_PROFILE AS M ON A.ID = M.MEMBER_ID
LEFT JOIN REST_REVIEW AS R ON A.ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;