SELECT 
    YEAR,
    BIG - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS A 
LEFT JOIN
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS BIG
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;