SELECT MAX(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E 
LEFT JOIN
    (SELECT SUM(SCORE) AS SCORE, EMP_NO FROM HR_GRADE GROUP BY EMP_NO, YEAR) G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;