SELECT 
    COUNT(ID) AS FISH_COUNT,
    MAX(A.LENGTH) AS MAX_LENGTH,
    A.FISH_TYPE
FROM FISH_INFO A
LEFT JOIN (SELECT 
            FISH_TYPE, 
            AVG(IFNULL(LENGTH, 10)) AS LENGTH 
           FROM FISH_INFO
            GROUP BY FISH_TYPE) B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.LENGTH >= 33
GROUP BY A.FISH_TYPE
ORDER BY FISH_TYPE ASC;